const jwt  = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const User = require("../models/User");


const generateToken = (userId) => {
    return jwt.sign(
    { id: userId },
    process.env.JWT_SECRET,
    { expiresIn: "7d" }
    );
};

const validatePassword =(password) => {
    if (!/[A-Z]/.test(password)) {
    throw new Error("Password must contain at least one capital letter,one number and one special character")
    }
if (!/[0-9]/.test(password)) {
    throw new Error("Password must contain at least one capital letter,one number and one special character")
    }
if (!/[!@#$%^&*]/.test(password)) {
    throw new Error("Password must contain at least one capital letter,one number and one special character")
    }
}

const registerUser =async ({ name, email, password }) => {

    validatePassword(password);

    const salt = await bcrypt.genSalt(10)
    const hashedPassword = await  bcrypt.hash(password,salt)
    const user = await User.create({name, email, password:hashedPassword});


    const token = generateToken(user._id);// user.id is the unique identifier for the user that is generated by MongoDB when the user is created. This ID is stored in the JWT token so that we can identify the user in future requests.

    return {
        user:{
            id:   user._id,
            name:  user.name,
            email: user.email,
        },
        token,
        };
    };


    const loginUser =async({email, password})=>{
        const user = await User.findOne({email});

        if(!user) return null;

        const isMatch = await bcrypt.compare(password,user.password);

        if(!isMatch)return null;

        const token =generateToken(user.id);

        return {
            user:{
                id:   user._id,
                name:  user.name,
                email: user.email,
            },
            token,
        };
    };

    module.exports = {registerUser,loginUser};


